### ISSUE TITLE
Danger and Primary style using the same color

### ISSUE THREAD

**Issue by Kharg** [novastream/Modern-Theme#1]
Danger and Primary style are using the same color; Orange #ff7a59.

I think they should use different colors instead of using the same.

Also success and primary are using the same color for other classes 0091ae (--brand-primary and --brand-success)

**Comment by novastream** [comment]
Thank you for the notices, I've updated danger colors to: #ff5962 and success colors to: #00bda5

**Comment by Kharg** [comment]
So much better now, thanks!
Something else that could be improved is the search bar as of now it blends with the background too much
![image](https://user-images.githubusercontent.com/32223252/211199787-46410c56-8400-4c98-8c68-c3107ef8a290.png)

**Comment by novastream** [comment]
Do you mean the main search in the upper right?

That bar should be darker like this:
![espo_search](https://user-images.githubusercontent.com/4106389/211200631-8e9d2902-d5b9-465b-a915-497b95084f5e.JPG)

**Comment by Kharg** [comment]
Oh, it's because I am using it with the vertical Sidebar, sorry.

**Comment by novastream** [comment]
No worries, I will have a look and see if I can fix the vertical sidebar as well but I think we need to find a more suiting color since the vertical navbar is bigger so it may look wierd if it is as dark as the horizontal navbar.

**Comment by Kharg** [comment]
As of now I am really liking the vertical navbar, maybe something that could be improved is the color when an entity is selected in the navbar 
![image](https://user-images.githubusercontent.com/32223252/211201093-79b336d8-d28d-4584-a076-27bc2200e1c1.png)

**Comment by novastream** [comment]
I see, maybe we can use the same color and make the buttons white like in the horizontal navbar and add some height to the navbar to give the search input a little more room?

![espo_search2](https://user-images.githubusercontent.com/4106389/211201287-2ab5d450-8f86-4ace-aa65-c459f87b22db.JPG)

**Comment by Kharg** [comment]
Usually other themes gives a different background to the search box, I don't know if making the whole top navbar dark blue is the best design choice
![image](https://user-images.githubusercontent.com/32223252/211201453-793f64d8-3905-42cc-9436-3878934cbe05.png)
![image](https://user-images.githubusercontent.com/32223252/211201470-8eea5621-ea3f-46f7-a752-3ccfbc90e7a5.png)
![image](https://user-images.githubusercontent.com/32223252/211201483-8deccf18-9e5f-4d20-bb67-f9e67a614137.png)

**Comment by novastream** [comment]
Agreed, maybe this lighter one could work or do you have a suggestion? :)

![espo_search3](https://user-images.githubusercontent.com/4106389/211201816-8d642e31-8ee8-42fb-864c-5957e6f5854d.JPG)

**Comment by Kharg** [comment]
This lighter one looks like it fits the style of the theme so well!

**Comment by novastream** [comment]
I will try to implement it this week so we can get the vertical navbar working :)

**Comment by Kharg** [comment]
Thanks, can't wait! :)

**Comment by Kharg** [comment]
Also something that I noticed,

The primary enum color is different than the primary button color, I think that the enum primary color would fit better for the buttons :) and maybe the current primary would be good for warning buttons/enums as their style was left unchanged.

**Comment by Kharg** [comment]
Also just noticed that the various Espo.Ui banners have all the same color
![image](https://user-images.githubusercontent.com/32223252/211249616-a7d04fa0-b79b-4ffc-bac7-fc9e62c30690.png)
![image](https://user-images.githubusercontent.com/32223252/211249639-ef63666b-e2fc-4504-821c-fb2dc7620647.png)
![image](https://user-images.githubusercontent.com/32223252/211249661-8c0f8983-caac-4429-bb52-2970eae72af5.png)

**Comment by novastream** [comment]
@Kharg this is something I'm working on right no as well as the height of the notifications :)

**Comment by Kharg** [comment]
@novastream Perfect! :)

What about New Checkboxes support for Espo 7.3.1?

**Comment by novastream** [comment]
I haven't updated my development enviroment yet but I would like the checkboxes to look something like this:
![checkboxes](https://user-images.githubusercontent.com/4106389/211549083-8a515fa9-4ded-44df-9ae8-36f1b34a2832.JPG)

**Comment by Kharg** [comment]
Yes, this design looks good! :)

**Comment by novastream** [comment]
@Kharg is there a new checkbox support for 7.3.1? Can't find it?

**Comment by Kharg** [comment]
@novastream here https://github.com/espocrm/espocrm/commit/51b621ecd11c1485b9b92febbf61c04b131ba0b0

**Comment by novastream** [comment]
Closing this issue for now since the initial issue is solved.
