### ISSUE TITLE
When copying, the background color is also copied

### ISSUE THREAD

**Issue by ChrisSka** [novastream/Modern-Theme#11]
I often have to copy something from another entry. Unfortunately, the background color is always copied as well.
This usually happens to me when I want to write a similar mail. I copy it out of the other mail and paste it into the new one.
The text is then always given the background color from the mail.
If I don't pay attention to this, the mails always look really stupid.
Is there any way to prevent this?

![image](https://github.com/user-attachments/assets/b05fb08a-ea81-4780-8d9e-0c15b01ea358)

**Comment by novastream** [comment]
Hi,

I will look in to this. I think its the nature of the wysiwyg editor and like other tools like Microsoft Word for example. A quick work-around is to use CTRL + SHIFT + V to paste the content as plain text (no formatting).

**Comment by novastream** [comment]
So after some research it seems that this is default behaviour from the browser. 

You can either paste what you are copying in to the code view (this will strip the formatting) or you can use a plugin like this one: https://mybrowseraddon.com/copy-as-plain-text.html

**Comment by ChrisSka** [comment]
Ok, then I know that it's not the template.
Then I always have to make sure when copying that it is copied unformatted.
