### ISSUE TITLE
Wrong Enum Color in Selectize 0.0.9

### ISSUE THREAD

**Issue by Kharg** [novastream/Modern-Theme#2]
Enum Warning during selection
![image](https://user-images.githubusercontent.com/32223252/211924059-1197a444-f54e-44d3-a580-8de2dacd2b5c.png)
Enum Warning after selection

![image](https://user-images.githubusercontent.com/32223252/211924089-9c57e0d1-c263-4f2e-9374-f752357fe328.png)

**Comment by novastream** [comment]
@Kharg this issue and some other issues have been fixed with the latest commit :)

**Comment by Kharg** [comment]
Thanks, I will test it as soon as possible :)

**Comment by Kharg** [comment]
Fixed, closing this issue
