### ISSUE TITLE
[Documentation] Readme Request - Screenshot

### ISSUE THREAD

**Issue by o-data** [novastream/Modern-Theme#3]
Hi Novastream,

Just found out you add these theme, was aware of your Hub theme but not this one. Would you kindly if you have time to add in maybe 1-2 screenshot as preview?

I'm stuck in a Dark Theme loop-hype but always like to see other theme style for idea and consideration to change theme.

Thank.

**Comment by novastream** [comment]
Hi @o-data 

Sorry for the late response, i've attached a couple of screenshots for you. Let me know if there are anything specific you want to see.

![list](https://user-images.githubusercontent.com/4106389/233833912-1dc74564-1a20-4831-b3bf-361c4db3203b.JPG)
![menu](https://user-images.githubusercontent.com/4106389/233833914-94a4a972-323b-4e0d-bc0e-d7f91d596ad6.JPG)
![settings](https://user-images.githubusercontent.com/4106389/233833918-4677d9e3-d94a-4403-abc5-b2b751fd877d.JPG)
![sidenav](https://user-images.githubusercontent.com/4106389/233833919-535619cf-8c39-438d-a26b-635f99611544.JPG)

**Comment by o-data** [comment]
Thank nova, nothing in particular. Just a few so people can make comparison and easier to make decision to install it.

**Comment by novastream** [comment]
Closing this issue, please open a new issue if anybody needs a specific screenshot.
