### ISSUE TITLE
Global search - error 500

### ISSUE THREAD

**Issue by ChrisSka** [novastream/Modern-Theme#4]
Hy, first of all respect for this theme. Looks really great. Only a little too bright.

But the problem I found, when I use the global search in the top corner, I always get the error 500.
And it comes no matter what I enter.

![IMG_20230509_231143_edit_1049265863504476](https://github.com/novastream/Modern-Theme/assets/68166740/119db4c6-0f3c-4997-9461-4093e236a034)

**Comment by novastream** [comment]
Thank you! 

Still working on the colors, kind of slow progress right now but we are getting there :)

Regarding your issue, could you open the inspector tool in your browser and look at the console and copy the 500 error. 

It's working fine on my part and shouldn't cause these kind of issues since the theme is only some CSS/LESS modifications.

**Comment by ChrisSka** [comment]
Update:

This has been resolved. I then suspected that another extension was to blame. After the first deactivation it already worked again.

It is this extension:
https://github.com/Bival1/crm-footer

**Comment by novastream** [comment]
Great!

Glad you got it sorted.

I see there is alot of template modifications in that extension, I guess it's not updated for the lasted version of Espo.

**Comment by ChrisSka** [comment]
Yes, it was just a test installation to change the footer. Instead, then only the creator of the extension is in the footer. Then I prefer to leave EspoCRM in it ;-)

What about the customization of the theme? Is it allowed to customize it to your own needs? So the colors that fit better to the company?

**Comment by novastream** [comment]
I thought it was something like that when I checked the source. You could change it with JavaScript or event with CSS by using something like this:
https://stackoverflow.com/questions/7896402/how-can-i-replace-text-with-css

Feel free to download, fork, modify as you wish. You could just change css or use the provided less files if you want to.

**Comment by ChrisSka** [comment]
For example, the following color appears in our company logo: #a4876a

And I would like to have it somehow in there.e.g. as a background color of each entity or in the dashboard, then it no longer comes across so bright.

**Comment by novastream** [comment]
You could use the browser inspector and look for the element / class and then you can use visual studio code or notepad++ and serach for it.

**Comment by ChrisSka** [comment]
hmmm.... really weird.
Got the color in the modern-iframe.css
for the attributes
--body-bg
--panel-bg
changed.
But unfortunately no change at all. Also cleared the cache. Nothing. It remains as it was. Do I have to change or delete something somewhere?

**Comment by novastream** [comment]
Try looking in the modern.css under the root variables. Remeber to clear the cache in espo and CTRL + F5 to reload the page.

**Comment by ChrisSka** [comment]
oh there it was in there. there i can search for a long time in the other file. Now it works. Thank you.

**Comment by novastream** [comment]
Closing this issue since the initial issue was resolved.
