### ISSUE TITLE
Missing fonts

### ISSUE THREAD

**Issue by ChrisSka** [novastream/Modern-Theme#5]
Hello,
after the EsoCRM update to 7.5.1
I get an error message that 3 fonts are missing.
![moderntheme](https://github.com/novastream/Modern-Theme/assets/68166740/b0e242ab-243b-4c69-a68a-e3519e26e00e)

**Comment by ChrisSka** [comment]
Ok, I was able to fix the upper error.
I had put the modern.css back on because I had made adjustments there.
But parts of it were changed and therefore the prompt font was not found.
But now the following error messages are displayed:
![moderntheme2](https://github.com/novastream/Modern-Theme/assets/68166740/0c6e3538-63c0-44ce-b945-916a9a7283ae)

I only get these error messages when I go to the backend.
This has something to do with the right column where EspoCRM advertises the official extensions.

**Comment by novastream** [comment]
Hi, seems like the resource is found but blocked by CORS policy. I don't have these issues in my production enviroment running 7.5.0 but I will check this week :)

Are you running Apache, nginx or any other proxy?

**Comment by ChrisSka** [comment]
My server was set to Apache. I switched to nginx as a test and see no difference.

**Comment by novastream** [comment]
Had some time over to look at the issue but I can't reproduce it in Espo 7.5.5.

**Comment by ChrisSka** [comment]
As far as I can see, this problem is no longer in 7.5.5.
After all, it didn't bother me. I actually came across it because of some other troubleshooting.

**Comment by ChrisSka** [comment]
As far as I can see, this problem is no longer in 7.5.5.
After all, it didn't bother me. I actually came across it because of some other troubleshooting.
