### ISSUE TITLE
Problem with the top menu.

### ISSUE THREAD

**Issue by Abid-Zakaria** [novastream/Modern-Theme#6]
When we have the three dots, the rest of the menu is unstable, and it is difficult to click on the other menu items.
![2023-11-12_16-03-42](https://github.com/novastream/Modern-Theme/assets/101017509/3b20200a-a61a-4375-b4f6-531f162a65c5)

**Comment by Abid-Zakaria** [comment]
https://github.com/novastream/Modern-Theme/assets/101017509/40bb3dd3-aee5-46a0-8748-27bd698a01f3

**Comment by novastream** [comment]
Thank you for your report and sorry for the late response. 

I've started to investigate the issue and found others that also have the same issue with bootstrap.
https://stackoverflow.com/questions/67971237/bootstrap-navbar-dropdown-flickering-not-working

I will get back to you as soon as its fixed :)

**Comment by novastream** [comment]
Issue has been resolved. Had to add mappedParams to the themes\Modern.json file.
