### ISSUE TITLE
Request for updating a field to make it compatible with EspoCRM version 8.1.0

### ISSUE THREAD

**Issue by Abid-Zakaria** [novastream/Modern-Theme#7]
Hello,
Request for updating a field to make it compatible with EspoCRM version 8.1.0
The phone number field should be updated to match the new phone field in international format.
<img width="606" alt="2" src="https://github.com/novastream/Modern-Theme/assets/101017509/c1e1af84-d8de-4a97-b099-97a33afd5025">
<img width="665" alt="ddd" src="https://github.com/novastream/Modern-Theme/assets/101017509/53f88404-1037-48ff-acb3-a87aaf7a4022">

**Comment by novastream** [comment]
@Feciam thank your for reporting this and providing screenshots. I will try to provide a update this week.

**Comment by ChrisSka** [comment]
It looks like it should work.
But it is only displayed for new entries.
If I want to edit an existing entry, the country code does not appear.

![image](https://github.com/novastream/Modern-Theme/assets/68166740/e6f101e9-e07c-413d-86aa-398eca855f78)

**Comment by novastream** [comment]
hmm, I'll have to check. I tried switch to the theme "Espo" and I got the same error. 

![image](https://github.com/novastream/Modern-Theme/assets/4106389/cd4bf969-fe8f-43c7-8fa9-1354ec646705)

**Comment by ChrisSka** [comment]
Ok, I have to correct myself.
You can already select the area code by clicking on the far left. Which was not obvious at first.

![image](https://github.com/novastream/Modern-Theme/assets/68166740/0d9126cc-993b-4b52-90e3-715dcc71fc86)

**Comment by novastream** [comment]
Closing the issue, thanks for reporting

**Comment by Abid-Zakaria** [comment]
Should I add something to the CSS file to fix the issue?

**Comment by novastream** [comment]
I've updated the theme, just download it from here once again and zip all the files inside the modules folder (except the do not upload directory) and upload as an extension :)

**Comment by Abid-Zakaria** [comment]
I customized it a bit in the theme, that's why I don't want to lose the customization.

**Comment by novastream** [comment]
Either you take the less changes from the below links or the precompiled css changes from the links below (modern.css)
https://github.com/novastream/Modern-Theme/commit/6f9da0445dcdf70e540adb6e89d7fd3dd610c113
https://github.com/novastream/Modern-Theme/commit/3043e0ca10d76c09fbcf53fa4044dc17c0c1a960
