### ISSUE TITLE
Missing styles?

### ISSUE THREAD

**Issue by ChrisSka** [novastream/Modern-Theme#8]
Could it be that the styles in the Modern Theme for the separators are still missing?
Here is an example from the Espo demo

![image](https://github.com/novastream/Modern-Theme/assets/68166740/8a44cb06-4208-4b94-8221-53230988bcf5)

**Comment by novastream** [comment]
These are not missing in the latest version :)

![image](https://github.com/novastream/Modern-Theme/assets/4106389/c0c4616c-ad9a-4b99-9004-b86289ae1bd8)

**Comment by ChrisSka** [comment]
I currently have version 1.1.8 of ModernTheme installed.
And I can hardly see the separator, as in the "CRM" example here.
I have heavily customised your theme, so I always have to check what you have changed.
I probably didn't notice that.

![image](https://github.com/novastream/Modern-Theme/assets/68166740/baec5ab0-75c5-42d1-82f7-fa20426703cf)

**Comment by novastream** [comment]
I understand but unfortunately I can't help you. I do less modifications and compile the less files as css. I would reccomend that if you modify the theme that you also merge the changes made to the less files and compile them your self. 

I did alot of merging from the original espo less files in the 2-3 latest commits.
