### ISSUE TITLE
Moved menu

### ISSUE THREAD

**Issue by ChrisSka** [novastream/Modern-Theme#9]
Hello,

can you help me with the following problem?
After updating EspoCRM, the small menu in the Kanban view has moved completely and is displayed somewhere on the page.

Here is the post in the EspoCRM forum:
https://forum.espocrm.com/forum/general/109818-has-anything-else-been-changed-in-kanban

**Comment by novastream** [comment]
I'll have a look at the issue and get back to you :)

**Comment by novastream** [comment]
The issue is resolved. I've updated dropdown.less to the latest version.

**Comment by ChrisSka** [comment]
Thank you very much, it's much better now.
